[[repos]]
repo = "builtin"
hooks = [
  { id = "fix-byte-order-marker", files = "\\.json$" },
  { id = "pretty-format-json", files = "\\.json$", args = ["--autofix", "--no-ensure-ascii"] },
  { id = "check-json", files = "\\.json$" },
]
